version: "3"
services:
  checkout:
    container_name: ygg-checkout
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    volumes:
      - "../dist:/usr/src/app/distbak"              